### ISSUE TITLE
ERRORS

### ISSUE THREAD

**Issue by SladeHazard** [ImOnlyFire/FireFreeze#2]
**Describe the bug**
Error in console once player used freeze keeps spamming console
**To Reproduce**
Happened randomly

**Expected behavior**
No errors

**Screenshots**

**Machine info (please complete the following information):**
 - Java Version: 8
 - Linux Version: 20.04 ubun
 - Plugin Version: 2.2
SErver VER 1.12.2

randomly once freeze cmd was used;
[15:15:34 WARN]: [FireFreeze] Plugin FireFreeze v2.2 generated an exception while executing task 144
java.lang.NullPointerException: null
        at me.onlyfire.firefreeze.tasks.FreezeMainTask.run(FreezeMainTask.java:37) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[server.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[server.jar:git-Paper-33d42c8e]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-33d42c8e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by SladeHazard** [comment]
stopped happening once unfroze the player please fix.

**Comment by literallyfiro** [comment]
Currently working for a fix, thank you for submitting.

**Comment by SladeHazard** [comment]
do you already know the fix/error if not I can send my config and log tmr

**Comment by literallyfiro** [comment]
I already found the problem, i'm testing right now

**Comment by literallyfiro** [comment]
Fixed (https://www.spigotmc.org/resources/firefreeze-2-0-titles-and-gui-support-fully-configurable-1-7-1-16.77105/update?update=410277)
